[tool.poetry]
name = "twod"
version = "0.1.5"
description = ""
authors = ["jnyjny <erik.oshaughnessy@gmail.com>"]
readme = 'README.rst'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.6"
coveralls = ""
pre-commit = "^1.17"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
